name: Run E2E Tests CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    services: 
      postigres:
        image: bitnami/postgresql
        ports:
          - 5432:5432
        environment:
          - POSTGRESQL_USERNAME=docker
          - POSTGRESQL_PASSWORD=docker
          - POSTGRESQL_DATABASE=apisolid

    steps:
      - uses: actions/checkout@v4
      - name: Run E2E Tests CI
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run test:e2e
        env:
          JWT_SECRET: anything
          DATABASE_URL: "postgresql://docker:docker@localhost:5432/apisolid?schema=public"
